name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature Request]: "
labels: ["fetaure"]
assignees:
  - magnus188
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
        
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature here...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation & Use Case
      description: Explain why this feature is important and how it would benefit you or other users.
      placeholder: For example, describe the problem this feature solves...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant details or context.
      placeholder: Additional details here...