name: Package Extension

on:
  pull_request:
    branches: ["main"]
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # -------------------------
      # HTML Lint (using HTMLHint or W3C Action)
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # -------------------------
      # Only if all lint steps pass, zip the extension
      - name: Zip the extension
        run: |
          zip -r extension.zip . \
            -x ".git*" \
            -x ".github*" \
            -x "README.md" \
            -x "*.yml"

      # -------------------------
      # Publish to Chrome Web Store
      - name: Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: 'extension.zip'
          extension_id: ${{ secrets.EXTENSION_ID }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          