name: Package Extension

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3


      # -------------------------
      # Extract version from manifest.json
      - name: Extract version from manifest
        id: extension_version
        run: |
          EXT_VERSION=$(jq -r '.version' manifest.json)
          echo "EXT_VERSION=$EXT_VERSION" >> $GITHUB_ENV

      

      # -------------------------
      # Zip the extension for Chrome Store and Github Releases
      - name: Zip the extension
        run: |
          zip -r amrop-extension.zip . \
            -x ".git*" \
            -x ".github*" \
            -x "docs/" \
            -x "docs/*" 
            -x "tests/" \
            -x "tests/*" \
            -x "package.json" \
            -x "playwright.config.ts" \

      # -------------------------
      # Create GitHub Release using version from manifest.json
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "beta"
          release_name: "v${{ env.EXT_VERSION }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # -------------------------
      # Publish to Chrome Web Store
      - name: Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: 'amrop-extension.zip'
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          